spring:
  servlet:
    multipart:
      max-request-size: 8GB
      max-file-size: 8GB
      file-size-threshold: 1MB
      location: /tmp/uploads
  data:
    mongodb:
      uri: mongodb://localhost:27017/food_insecurity_db